spring:
  application:
    name: transfers

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [traceId=%X{traceId:-}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.challenge.transfers: DEBUG
    org.springframework.ws: WARN
